name: Deploy to K3s

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Configure Kubeconfig
        run: |
          echo "${{ secrets.KUBECONFIG }}" | base64 --decode > kubeconfig.yaml
          export KUBECONFIG=$PWD/kubeconfig.yaml

      - name: Install Vault CLI
        run: |
          curl -fsSL https://apt.releases.hashicorp.com/gpg | sudo apt-key add -
          sudo apt-add-repository "deb [arch=amd64] https://apt.releases.hashicorp.com focal main"
          sudo apt-get update && sudo apt-get install vault -y

      - name: Authenticate with Vault & Retrieve Secrets
        run: |
          export VAULT_ADDR='${{ secrets.VAULT_ADDR }}'
          vault login ${{ secrets.VAULT_TOKEN }}
          username=$(vault kv get -field=username secret/myapp)
          password=$(vault kv get -field=password secret/myapp)
          echo "USERNAME=$username" >> $GITHUB_ENV
          echo "PASSWORD=$password" >> $GITHUB_ENV

      - name: Create Kubernetes Secret
        run: |
          kubectl create secret generic myapp-secret \
            --from-literal=username="$USERNAME" \
            --from-literal=password="$PASSWORD" \
            --dry-run=client -o yaml | kubectl apply -f -

      - name: Deploy to K3s
        run: |
          kubectl apply -f nginx-deployment.yaml
          kubectl rollout restart deployment nginx

